version: '2'
services:
  led-strip-driver:
    build: ./led-strip-driver
#    environment:
#      - MAX_NUM_PIXELS=10 #superseded with dashboard Device Variables now we've left local mode.
    restart: always
    privileged: true # bugger, necessary due to: https://github.com/moby/moby/issues/43419
    devices:
      - "/dev/mem:/dev/mem"   # for rpi_ws281x, prevents "ws2811_init failed with code -5 (mmap() failed)"
      - "/dev/vcio:/dev/vcio" # for rpi_ws281x, prevents "ws2811_init failed with code -9 (Failed to create mailbox device)"
    cap_add:
      - SYS_RAWIO
    ports:
      - "80:80" # temporary to make it easier to test
  winot-gui:
    build: ./winot-gui
    environment:
      - UDEV=1
    privileged: true
    restart: always
# dri/card0 is sufficient for the display. Alas while /dev/input is properly populated with
# event0, event1, mice and mouse0, and the EDT FT5406 driver (edt-ft5x06) appears in lsmod,
# no permutations of mapping/mounting the contents of /dev/input will enable touch. So we
# resort to privileged + balenalib's magic UDEV=1 instead, because it works. Ain't Docker fun?
#    devices:
#      - "/dev/dri/card0:/dev/dri/card0"       # This is sufficient for the display.
