version: '2'
services:
  led-strip-driver:
    build: ./led-strip-driver
    environment:
      - MAX_NUM_PIXELS=10 #TODO: supersede with dashboard Device Variables when we leave local mode.
    restart: always
    devices:
      - "/dev/mem:/dev/mem"   # for rpi_ws281x, prevents "ws2811_init failed with code -5 (mmap() failed)"
      - "/dev/vcio:/dev/vcio" # for rpi_ws281x, prevents "ws2811_init failed with code -9 (Failed to create mailbox device)"
    cap_add:
      - SYS_RAWIO
    ports:
      - "80:80" # temporary to make it easier to test
  
  browser:
    image: balenablocks/browser
    environment:
      - KIOSK=1
    #TODO: likely useful to pick up the barcode scanner, but is there a smaller sledgehammer I can use?
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host #TODO: why?
#    ports:
#        - '5011' # management API (optional)
#        - '35173' # Chromium debugging port (optional)
#    volumes:
#      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
