FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.9-build

WORKDIR /usr/src/app

RUN \
    apt-get update && apt-get upgrade -y 

RUN \
    pip3 install RPi.GPIO requests

COPY *.py ./

CMD ["sleep", "infinity"]
